version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: btc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  fetcher:
    build: ./fetcher
    depends_on:
      - nuxtapp

  nuxtapp:
    build: ./nuxtapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/btc?schema=public
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
    depends_on:
      - postgres

volumes:
  pgdata:
